kafka:
  enabled: true
  kraft:
    enabled: true
  replicas: 1
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi
  persistence:
    enabled: true
    size: 10Gi
    storageClass: default
  configurationOverrides:
    "offsets.topic.replication.factor": "1"
    "transaction.state.log.replication.factor": "1"
    "transaction.state.log.min.isr": "1"
  service:
    type: LoadBalancer

schema-registry:
  enabled: true

kafka-rest:
  enabled: true

zookeeper:
  enabled: false

controlcenter:
  enabled: false
connect:
  enabled: false
ksqldb:
  enabled: false
replicator:
  enabled: false
